# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'firstPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(885, 610)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LabelUsername = QtWidgets.QLabel(self.centralwidget)
        self.LabelUsername.setGeometry(QtCore.QRect(250, 140, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.LabelUsername.setFont(font)
        self.LabelUsername.setObjectName("LabelUsername")
        self.labelPassword = QtWidgets.QLabel(self.centralwidget)
        self.labelPassword.setGeometry(QtCore.QRect(250, 250, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelPassword.setFont(font)
        self.labelPassword.setObjectName("labelPassword")
        self.titleLogin = QtWidgets.QLabel(self.centralwidget)
        self.titleLogin.setGeometry(QtCore.QRect(10, 40, 871, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.titleLogin.setFont(font)
        self.titleLogin.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLogin.setObjectName("titleLogin")
        self.loginButton = QtWidgets.QPushButton(self.centralwidget)
        self.loginButton.setGeometry(QtCore.QRect(250, 410, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.loginButton.setFont(font)
        self.loginButton.setObjectName("loginButton")
        self.signupButton = QtWidgets.QPushButton(self.centralwidget)
        self.signupButton.setGeometry(QtCore.QRect(420, 410, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.signupButton.setFont(font)
        self.signupButton.setObjectName("signupButton")
        self.inputUsername = QtWidgets.QLineEdit(self.centralwidget)
        self.inputUsername.setGeometry(QtCore.QRect(250, 190, 421, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.inputUsername.setFont(font)
        self.inputUsername.setObjectName("inputUsername")
        self.inputPassword = QtWidgets.QLineEdit(self.centralwidget)
        self.inputPassword.setGeometry(QtCore.QRect(250, 310, 421, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.inputPassword.setFont(font)
        self.inputPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.inputPassword.setObjectName("inputPassword")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1, 510, 881, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 885, 30))
        self.menubar.setObjectName("menubar")
        self.menuAction = QtWidgets.QMenu(self.menubar)
        self.menuAction.setObjectName("menuAction")
        self.menuTheme = QtWidgets.QMenu(self.menuAction)
        self.menuTheme.setObjectName("menuTheme")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAdd_User = QtWidgets.QAction(MainWindow)
        self.actionAdd_User.setObjectName("actionAdd_User")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionLight = QtWidgets.QAction(MainWindow)
        self.actionLight.setObjectName("actionLight")
        self.actionDark = QtWidgets.QAction(MainWindow)
        self.actionDark.setObjectName("actionDark")
        self.actionQuit_2 = QtWidgets.QAction(MainWindow)
        self.actionQuit_2.setObjectName("actionQuit_2")
        self.menuTheme.addAction(self.actionLight)
        self.menuTheme.addAction(self.actionDark)
        self.menuAction.addAction(self.menuTheme.menuAction())
        self.menuAction.addAction(self.actionQuit_2)
        self.menubar.addAction(self.menuAction.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.loginButton.clicked.connect(self.actionHandleLogin)
        self.signupButton.clicked.connect(self.actionHandleSignUp)
        # self.actionLight.clicked.connect(lambda: self.actionChangeTheme('light'))
        # self.actionDark.clicked.connect(lambda: self.actionChangeTheme('dark'))
        # self.actionQuit_2.clicked.connect(self.actionAppExit)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "User Login"))
        MainWindow.setStatusTip(_translate("MainWindow", "Enter Password"))
        self.LabelUsername.setText(_translate("MainWindow", "Username"))
        self.labelPassword.setText(_translate("MainWindow", "Password"))
        self.titleLogin.setText(_translate("MainWindow", "Authentication System"))
        self.loginButton.setText(_translate("MainWindow", "Login"))
        self.signupButton.setText(_translate("MainWindow", "SignUp"))
        self.inputUsername.setStatusTip(_translate("MainWindow", "Enter Username"))
        self.inputPassword.setStatusTip(_translate("MainWindow", "Enter Password"))
        self.label.setText(_translate("MainWindow", "Developed By develSanx"))
        self.menuAction.setTitle(_translate("MainWindow", "Preference"))
        self.menuTheme.setTitle(_translate("MainWindow", "Theme"))
        self.actionAdd_User.setText(_translate("MainWindow", "Add User"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionLight.setText(_translate("MainWindow", "Light"))
        self.actionDark.setText(_translate("MainWindow", "Dark"))
        self.actionQuit_2.setText(_translate("MainWindow", "Quit"))

    def actionHandleLogin(self):
        print("Login")
    
    def actionHandleSignUp(self):
        print("Signup")
    
    def actionChangeTheme(self, theme):
        print("Theme Changed to %s" % theme)
    
    def actionAppExit(self):
        print("App Quit")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
